
import React, { useState, useCallback, useRef } from 'react';
import { generateProposal } from '../services/geminiService';
import { Spinner } from './Spinner';
import { ProposalIcon, DownloadIcon } from './icons';
import type { ProposalOutput, ProposalStyle } from '../types';

interface ProposalGeneratorViewProps {
    onBack: () => void;
}

const STYLES: ProposalStyle[] = ['Corporate / Formal', 'Friendly / Casual', 'Technical / Engineering', 'Creative / Marketing'];
const THEMES = [
    { name: 'Indigo', color: '#4F46E5', bg: '#EEF2FF' },
    { name: 'Emerald', color: '#059669', bg: '#ECFDF5' },
    { name: 'Rose', color: '#E11D48', bg: '#FFF1F2' },
    { name: 'Slate', color: '#475569', bg: '#F8FAFC' },
];

export const ProposalGeneratorView: React.FC<ProposalGeneratorViewProps> = ({ onBack }) => {
    // Input State
    const [clientName, setClientName] = useState('');
    const [projectType, setProjectType] = useState('');
    const [goals, setGoals] = useState('');
    const [budget, setBudget] = useState('');
    const [timeline, setTimeline] = useState('');
    const [style, setStyle] = useState<ProposalStyle>(STYLES[0]);
    const [logo, setLogo] = useState<string | null>(null);
    const [theme, setTheme] = useState(THEMES[0]);
    
    // Result State
    const [result, setResult] = useState<ProposalOutput | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleLogoUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onloadend = () => {
                setLogo(reader.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const handleGenerate = useCallback(async () => {
        if (!clientName || !projectType || !goals) {
            alert('Please fill in the Client Name, Project Type, and Goals.');
            return;
        }
        setIsLoading(true);
        try {
            const proposal = await generateProposal(clientName, projectType, goals, budget, timeline, style);
            setResult(proposal);
        } catch (error) {
            console.error("Proposal generation failed:", error);
            alert("Failed to generate proposal. Please try again.");
        } finally {
            setIsLoading(false);
        }
    }, [clientName, projectType, goals, budget, timeline, style]);

    const handlePrint = () => {
        const printContent = document.getElementById('proposal-preview');
        if (printContent) {
            const win = window.open('', '', 'width=800,height=900');
            if (win) {
                win.document.write(`
                    <html>
                        <head>
                            <title>${result?.title || 'Proposal'}</title>
                            <style>
                                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; line-height: 1.6; }
                                h1 { font-size: 28px; color: #111; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px; }
                                h2 { font-size: 20px; color: ${theme.color}; margin-top: 30px; margin-bottom: 10px; }
                                h3 { font-size: 16px; font-weight: bold; margin-top: 20px; }
                                p { margin-bottom: 15px; }
                                ul { margin-bottom: 15px; padding-left: 20px; }
                                li { margin-bottom: 5px; }
                                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                                th, td { padding: 12px; border-bottom: 1px solid #ddd; text-align: left; }
                                th { background-color: ${theme.bg}; font-weight: 600; }
                                .header { margin-bottom: 40px; display: flex; justify-content: space-between; align-items: center; }
                                .logo { max-height: 60px; max-width: 200px; }
                                .meta { color: #666; font-size: 14px; margin-bottom: 40px; }
                                .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
                            </style>
                        </head>
                        <body>
                            ${printContent.innerHTML}
                            <div class="footer">Generated by SmartWriter AI Proposal Tool</div>
                        </body>
                    </html>
                `);
                win.document.close();
                win.focus();
                setTimeout(() => {
                    win.print();
                    win.close();
                }, 500);
            }
        }
    };

    return (
        <div className="p-4 md:p-6 h-full flex flex-col bg-indigo-50">
            {isLoading && <Spinner message="Drafting professional proposal..." />}
            
            <div className="flex items-center justify-between mb-6">
                 <button onClick={onBack} className="flex items-center text-sm font-semibold text-indigo-700 hover:text-indigo-900 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
                    Back to Tools
                </button>
                <div className="flex items-center gap-3">
                    <h1 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
                        <ProposalIcon className="h-7 w-7 text-indigo-600" />
                        Proposal Generator
                    </h1>
                </div>
                 {result && (
                    <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-indigo-200 text-indigo-800 font-semibold rounded-lg hover:bg-indigo-300 transition">
                        <DownloadIcon className="h-4 w-4" />
                        Print / PDF
                    </button>
                )}
            </div>

            <div className="flex flex-col lg:flex-row gap-6 h-full overflow-hidden">
                {/* Input Panel */}
                <div className="w-full lg:w-1/3 flex-shrink-0 bg-white border border-indigo-200 rounded-xl p-5 h-full flex flex-col shadow-sm overflow-y-auto">
                    <h2 className="text-lg font-bold text-gray-800 mb-4 border-b pb-2">Project Intake</h2>
                    
                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-1">Branding (Logo)</label>
                            <div 
                                className="w-full h-16 border-2 border-dashed border-gray-300 rounded-lg flex items-center justify-center cursor-pointer hover:border-indigo-400 hover:bg-indigo-50 transition"
                                onClick={() => fileInputRef.current?.click()}
                            >
                                <input type="file" ref={fileInputRef} onChange={handleLogoUpload} className="hidden" accept="image/*" />
                                {logo ? <img src={logo} alt="Logo" className="h-12 object-contain" /> : <span className="text-xs text-gray-500 font-medium">Click to upload logo</span>}
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-1">Color Theme</label>
                            <div className="flex gap-2">
                                {THEMES.map(t => (
                                    <button 
                                        key={t.name}
                                        onClick={() => setTheme(t)}
                                        className={`w-8 h-8 rounded-full border-2 ${theme.name === t.name ? 'border-gray-600 scale-110' : 'border-transparent'}`}
                                        style={{ backgroundColor: t.color }}
                                        title={t.name}
                                    />
                                ))}
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-1">Client Name</label>
                            <input
                                type="text"
                                value={clientName}
                                onChange={(e) => setClientName(e.target.value)}
                                placeholder="e.g. Acme Corp"
                                className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-gray-700 focus:ring-2 focus:ring-indigo-500 focus:outline-none transition"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-1">Project Type</label>
                            <input
                                type="text"
                                value={projectType}
                                onChange={(e) => setProjectType(e.target.value)}
                                placeholder="e.g. Website Redesign, Marketing Audit"
                                className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-gray-700 focus:ring-2 focus:ring-indigo-500 focus:outline-none transition"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-1">Goals & Requirements</label>
                            <textarea
                                value={goals}
                                onChange={(e) => setGoals(e.target.value)}
                                placeholder="What does the client want to achieve? Any specific deliverables?"
                                className="w-full h-32 bg-gray-50 border border-gray-300 rounded-lg p-3 text-gray-700 focus:ring-2 focus:ring-indigo-500 focus:outline-none transition resize-none"
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-3">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-1">Budget Hint</label>
                                <input
                                    type="text"
                                    value={budget}
                                    onChange={(e) => setBudget(e.target.value)}
                                    placeholder="e.g. $5k - $10k"
                                    className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-gray-700 focus:ring-2 focus:ring-indigo-500 focus:outline-none transition"
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-1">Timeline Hint</label>
                                <input
                                    type="text"
                                    value={timeline}
                                    onChange={(e) => setTimeline(e.target.value)}
                                    placeholder="e.g. 2 months"
                                    className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-gray-700 focus:ring-2 focus:ring-indigo-500 focus:outline-none transition"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-gray-700 mb-2">Proposal Style</label>
                            <select 
                                value={style}
                                onChange={(e) => setStyle(e.target.value as ProposalStyle)}
                                className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-gray-700 focus:ring-2 focus:ring-indigo-500 focus:outline-none transition"
                            >
                                {STYLES.map(s => <option key={s} value={s}>{s}</option>)}
                            </select>
                        </div>
                    </div>

                    <button 
                        onClick={handleGenerate} 
                        disabled={isLoading || !clientName || !projectType}
                        className="w-full mt-6 py-3 bg-indigo-600 text-white font-bold text-lg rounded-xl hover:bg-indigo-700 disabled:bg-indigo-300 disabled:cursor-not-allowed transition-all transform hover:scale-105 shadow-lg"
                        style={{ backgroundColor: theme.color }}
                    >
                        Generate Proposal
                    </button>
                </div>

                {/* Output Panel (Preview) */}
                <div className="w-full lg:w-2/3 bg-white border border-indigo-200 rounded-xl h-full flex flex-col shadow-sm overflow-hidden">
                    {!result ? (
                        <div className="flex flex-col items-center justify-center h-full text-gray-400 p-8 text-center">
                            <ProposalIcon className="h-16 w-16 mb-4 text-indigo-200" />
                            <h3 className="text-xl font-semibold text-gray-500">Ready to Win Clients?</h3>
                            <p className="mt-2 max-w-md">Enter the project details to generate a complete, professional proposal instantly.</p>
                        </div>
                    ) : (
                        <div className="flex-grow overflow-y-auto p-8 lg:p-12 bg-white">
                            <div id="proposal-preview" className="max-w-3xl mx-auto">
                                <div className="header border-b-2 border-gray-100 pb-6 mb-8 flex justify-between items-center">
                                    <div>
                                        {logo && <img src={logo} alt="Company Logo" className="logo mb-4 h-12 object-contain" />}
                                        <h1 className="text-4xl font-bold text-gray-900 mb-2">{result.title}</h1>
                                        <div className="meta text-gray-500 font-medium">
                                            Prepared for: <span className="text-gray-800">{clientName}</span> • Date: {new Date().toLocaleDateString()}
                                        </div>
                                    </div>
                                </div>

                                <div className="space-y-8 text-gray-700 leading-relaxed">
                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Executive Summary</h2>
                                        <p>{result.executiveSummary}</p>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Project Overview</h2>
                                        <p>{result.projectOverview}</p>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Scope of Work</h2>
                                        <ul className="list-disc list-outside ml-5 space-y-1">
                                            {result.scopeOfWork.map((item, i) => <li key={i}>{item}</li>)}
                                        </ul>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Deliverables</h2>
                                        <ul className="list-disc list-outside ml-5 space-y-1">
                                            {result.deliverables.map((item, i) => <li key={i}>{item}</li>)}
                                        </ul>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Timeline</h2>
                                        <div className="overflow-x-auto">
                                            <table className="w-full text-left border-collapse">
                                                <thead>
                                                    <tr className="border-b border-gray-200" style={{ backgroundColor: theme.bg }}>
                                                        <th className="py-2 px-3 font-semibold text-gray-700">Phase</th>
                                                        <th className="py-2 px-3 font-semibold text-gray-700">Duration</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {result.timeline.map((t, i) => (
                                                        <tr key={i} className="border-b border-gray-100">
                                                            <td className="py-2 px-3">{t.phase}</td>
                                                            <td className="py-2 px-3 text-gray-600">{t.duration}</td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Investment</h2>
                                        <div className="overflow-x-auto">
                                            <table className="w-full text-left border-collapse">
                                                <thead>
                                                    <tr className="border-b border-gray-200" style={{ backgroundColor: theme.bg }}>
                                                        <th className="py-2 px-3 font-semibold text-gray-700">Item</th>
                                                        <th className="py-2 px-3 font-semibold text-gray-700 text-right">Cost</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {result.pricing.map((p, i) => (
                                                        <tr key={i} className="border-b border-gray-100">
                                                            <td className="py-2 px-3">{p.item}</td>
                                                            <td className="py-2 px-3 text-right font-medium text-gray-900">{p.cost}</td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </div>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Why Choose Us?</h2>
                                        <p>{result.whyChooseUs}</p>
                                    </section>

                                    <section>
                                        <h2 className="text-xl font-bold uppercase tracking-wide mb-3" style={{ color: theme.color }}>Terms & Conditions</h2>
                                        <ul className="list-disc list-outside ml-5 space-y-1 text-sm text-gray-600">
                                            {result.termsAndConditions.map((item, i) => <li key={i}>{item}</li>)}
                                        </ul>
                                    </section>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};
